### ISSUE TITLE
MowstGCN Results on Flickr and Penn94 Datasets Differ Significantly from Paper Results

### ISSUE THREAD

**Issue by Season111** [facebookresearch/mowst-gnn#1]
Thank you very much for sharing the code and for the valuable insights in your paper! While reproducing the results, I followed the parameter settings as described, but noticed that my results for MowstGCN on the Flickr and Penn94 datasets differ somewhat from those reported.

If possible, could you kindly offer some guidance on achieving results closer to those in the paper? I am wondering if adding model pre-training or any additional adjustments might be recommended.

Thank you in advance for your assistance and for your contributions to the field!

**Comment by brucelyu17** [comment]
> Thank you very much for sharing the code and for the valuable insights in your paper! While reproducing the results, I followed the parameter settings as described, but noticed that my results for MowstGCN on the Flickr and Penn94 datasets differ somewhat from those reported.
> 
> If possible, could you kindly offer some guidance on achieving results closer to those in the paper? I am wondering if adding model pre-training or any additional adjustments might be recommended.
> 
> Thank you in advance for your assistance and for your contributions to the field!

Hi,

Thank you for reaching out and for your interest in our work! The detailed setting for MowstGCN on Flickr and Penn94 are as follows:

Flickr:
```
--method mowst --submethod pretrain_model2 --subloss separate --infer_method multi
```

Penn94
```
--method mowst_star --submethod pretrain_model2 --subloss joint --infer_method joint --no_cached --crit crossentropy
```

Best,
Hanjia
